/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.aptecic.racecalendar;

/**
 *
 * @author Manuel G. Najera (najera_manuel_g@cat.com)
 */
public class RaceApp extends javax.swing.JFrame {

    RaceList raceList;
    
    /**
     * Creates new form RaceApp
     */
    public RaceApp() {
        initComponents();
        raceList = new RaceList();
        raceAppDesktop.add(raceList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        raceAppDesktop = new javax.swing.JDesktopPane();
        raceAppMenu = new javax.swing.JMenuBar();
        mnuSystem = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        mnuRace = new javax.swing.JMenu();
        mnuRaceList = new javax.swing.JMenuItem();
        mnuTraining = new javax.swing.JMenu();
        mnuCalGen = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        raceAppDesktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout raceAppDesktopLayout = new javax.swing.GroupLayout(raceAppDesktop);
        raceAppDesktop.setLayout(raceAppDesktopLayout);
        raceAppDesktopLayout.setHorizontalGroup(
            raceAppDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        raceAppDesktopLayout.setVerticalGroup(
            raceAppDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        mnuSystem.setText("System");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuSystem.add(mnuExit);

        raceAppMenu.add(mnuSystem);

        mnuRace.setText("Races");

        mnuRaceList.setText("Race List");
        mnuRaceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRaceListActionPerformed(evt);
            }
        });
        mnuRace.add(mnuRaceList);

        raceAppMenu.add(mnuRace);

        mnuTraining.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.acceleratorForeground"));
        mnuTraining.setText("Training");

        mnuCalGen.setText("Generate Training Calendar");
        mnuCalGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalGenActionPerformed(evt);
            }
        });
        mnuTraining.add(mnuCalGen);

        raceAppMenu.add(mnuTraining);

        setJMenuBar(raceAppMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(raceAppDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(raceAppDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuCalGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalGenActionPerformed
        CalendarGenerator calendarGenerator = new CalendarGenerator();
        raceAppDesktop.add(calendarGenerator);
        calendarGenerator.setVisible(true);
    }//GEN-LAST:event_mnuCalGenActionPerformed

    private void mnuRaceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRaceListActionPerformed
        raceList.setVisible(true);        
    }//GEN-LAST:event_mnuRaceListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaceApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaceApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuCalGen;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuRace;
    private javax.swing.JMenuItem mnuRaceList;
    private javax.swing.JMenu mnuSystem;
    private javax.swing.JMenu mnuTraining;
    private javax.swing.JDesktopPane raceAppDesktop;
    private javax.swing.JMenuBar raceAppMenu;
    // End of variables declaration//GEN-END:variables
}
